language: node_js
node_js:
- '8'
before_deploy: "npm run build"
deploy:
  provider: npm
  skip_cleanup: true
  email: a8568730@gmail.com
  api_key: ${NPM_TOKEN}
  on:
    tags: true
    repo: i3thuan5/demo-ui
